[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pip"
version = "24.2"
description = "An example project configuration for pip"
authors = [
    {name = "Darien Allison", email = "Dall8536@students.vsu.edu"}
]
